# Generated by Django 4.2.15 on 2024-09-16 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sluf',
            new_name='slug',
        ),
    ]
