# Generated by Django 5.1.6 on 2025-03-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$tgeGFGnPHrky8nMluqqSKT$sEoJiN0+IntOMD6Y60pyZ7bccPbuJUQVEXHhuDmDqDI=', max_length=128),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
