# Generated by Django 5.1.6 on 2025-03-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_author_password_alter_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$lehDIlz6eKhlia7OVCFPX0$P2n3tm3w0SfbbPIGe96tEKd28+goT1gJeC5hUlA0kjY=', max_length=128),
        ),
    ]
