# Generated by Django 5.1.6 on 2025-03-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_author_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='author',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$hMgu02XHsZ2JKEjcEaBmft$HmRTMZFB/10V8qaCDQcNrj6m3+2R9KmbbVgHTuSGg8M=', max_length=128),
        ),
    ]
