# Generated by Django 4.2.15 on 2024-09-17 14:43

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='projects/', validators=[home.models.validate_image_extension]),
        ),
    ]
