# Generated by Django 4.2.15 on 2024-09-17 15:03

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('image', models.ImageField(upload_to='websites/', validators=[home.models.validate_image_extension])),
                ('title', models.CharField(max_length=200)),
                ('description1', models.TextField(blank=True)),
                ('description2', models.TextField(blank=True)),
                ('projectImage', models.ImageField(upload_to='websites/', validators=[home.models.validate_image_extension])),
            ],
        ),
    ]
