# Generated by Django 4.2.15 on 2024-09-17 15:28

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='image',
            field=models.FileField(upload_to='websites/', validators=[home.models.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='website',
            name='projectImage',
            field=models.FileField(upload_to='websites/', validators=[home.models.validate_image_extension]),
        ),
    ]
