# Generated by Django 4.2.15 on 2024-09-17 17:11

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_website_image_alter_website_projectimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('span', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.FileField(upload_to='home/', validators=[home.models.validate_image_extension])),
            ],
        ),
    ]
