# Generated by Django 4.2.15 on 2024-09-19 16:20

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(max_length=50)),
                ('customerdesignation', models.CharField(max_length=50)),
                ('customerimage', models.FileField(upload_to='rcustomer/', validators=[home.models.validate_image_extension])),
                ('customerreview', models.TextField()),
            ],
        ),
    ]
