# Generated by Django 4.2.15 on 2024-09-19 16:45

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(upload_to='projects/', validators=[home.models.validate_image_extension]),
        ),
    ]
