# Generated by Django 4.2.15 on 2024-09-19 17:59

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=50)),
                ('e_position', models.CharField(max_length=50)),
                ('e_designation', models.CharField(max_length=50)),
                ('e_image', models.FileField(upload_to='teams/', validators=[home.models.validate_image_extension])),
                ('e_facebook', models.URLField()),
                ('e_instagram', models.URLField()),
                ('e_linkedin', models.URLField()),
                ('e_github', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='customerreview',
            field=models.CharField(max_length=150),
        ),
    ]
