# Generated by Django 4.2.15 on 2024-09-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_team_alter_review_customerreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='e_github',
            field=models.URLField(blank=True),
        ),
    ]
