# Generated by Django 4.2.15 on 2024-09-20 16:04

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_team_e_github'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('t_project', models.CharField(max_length=50)),
                ('t_country', models.CharField(max_length=50)),
                ('o_project', models.CharField(max_length=50)),
                ('view', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='about/', validators=[home.models.validate_image_extension])),
            ],
        ),
    ]
